apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    name: ubuntu-test-replica
  name: ubuntu-test-replica
  namespace: sock-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ubuntu-test-replica
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ubuntu-test-replica
    spec:
      containers:
        - name: ubuntu-container-replica
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command: ["/bin/bash"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
